version: "3"
services:
  pigeoncoin:
    image: lukepighetti/pigeon-docker
    restart: always
    ports:
      - "8757:8757"
    command: "pigeond -txindex -rpcuser=rpc_user -rpcpassword=rpc_password -rpcport=8757 -rpcallowip=0.0.0.0/0"

  mongo:
    build: ./explorer-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: explorer_database

  explorer:
    build:
      dockerfile: Dockerfile
      context: ./explorer
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      # - pigeoncoin
