version: "3"
services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      # - "80:80"
      # - "443:443"
      - "3000:3000"
    depends_on:
      - explorer
      - api-server
      - website

  pigeoncoin:
    image: lukepighetti/pigeoncoin
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"

  mongo:
    build: ./explorer/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database
    volumes:
      - "database_data:/data/db"

  explorer:
    build: ./explorer/express
    restart: always
    depends_on:
      - mongo
      - pigeoncoin
    environment:
      SUB_PATH: /explorer
      BACK_URL: /

  bot:
    build: ./bot
    restart: always

  api-server:
    build: ./api-server
    restart: always

  api-collector:
    build: ./api-collector/collector
    restart: always
    depends_on:
      - pigeoncoin
    environment:
      RPC_HOST: pigeoncoin
      FETCH_HISTORICAL_MINUTES: 5
      RTDB_URL: https://scratch-project-9f138.firebaseio.com

  website:
    build: ./website
    restart: always

  seeder:
    build: ./seeder
    restart: always
    ports:
      - "5353:53"

volumes:
  chain_data:
  database_data:
