version: "3"
services:
  pigeoncoin:
    image: "lukepighetti/pigeon-docker:next"
    restart: always

  mongo:
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      # MONGO_INITDB_DATABASE: explorer_database

  explorer:
    build:
      dockerfile: Dockerfile
      context: ./explorer
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - pigeoncoin
