version: "3"
services:
  pigeoncoin:
    build: ./pigeoncoin
    restart: always

  collector:
    build: ./collector
    restart: always
    depends_on:
      - pigeoncoin
    environment:
      RPC_HOST: pigeoncoin
