version: "3"
services:
  pigeoncoin:
    build: ./pigeoncoin
    restart: always

  mongo:
    build: ./db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database

  explorer:
    build: ./express
    restart: always
    ports:
      - "3000:3001"
    depends_on:
      - mongo
      - pigeoncoin
      