version: "3"
services:
  pigeoncoin:
    image: lukepighetti/pigeoncoin:latest
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"

  mongo:
    build: ./db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database
    volumes:
      - "database_data:/data/db"

  explorer:
    build: ./express
    restart: always
    ports:
      - "3000:3001"
    depends_on:
      - mongo
      - pigeoncoin

volumes:
  chain_data:
  database_data:
