version: "3"
services:
  pigeoncoin:
    build: ./pigeoncoin
    restart: always
    volumes:
      - "chain_data:/root/.pigeon"

  mongo:
    build: ./db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: explorer_database
    volumes:
      - "database_data:/data/db"

  explorer:
    build: ./express
    restart: always
    ports:
      - "3000:3001"
    depends_on:
      - mongo
      - pigeoncoin

volumes:
  chain_data:
  database_data:
