title: Pigeoncoin
email: contact@pigeoncoin.org
tagline: Digital freedom
description: >
  Messaging and payments for everyone. Security by Blockchain.

notice:
  show: false
  address: https://github.com/Pigeoncoin/pigeoncoin/releases/tag/v0.15.99.6
  text: Critical wallet update. Upgrade to 15.99.6.
  color: has-text-danger #success, warning, danger, info, primary, secondary


# config
baseurl: null # baseurl: null # when deployed to pigeoncoin.org

# social links
social:
    Discord: https://discord.gg/SZcf63h
    Twitter: https://twitter.com/Pigeoncoin
    Github: https://github.com/Pigeoncoin
    Reddit: https://www.reddit.com/r/Pigeoncoin/
    Telegram: https://t.me/Pigeoncoin
    Medium: https://medium.com/@pigeoncoin

# download links
wallets:
  macOS: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.6/pigeon_0.15.99.6_macHighSierra.tar.gz
  Windows: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.6/pigeon_0.15.99.6_win64.zip
  Linux: https://github.com/Pigeoncoin/pigeoncoin/releases/download/v0.15.99.6/pigeon_0.15.99.6_ubuntu16.tar.gz

miners:
  Nvidia: https://github.com/brian112358/nevermore-miner/releases/
  AMD: https://github.com/brian112358/avermore-miner/releases

exchanges:
  CryptoBridge: https://crypto-bridge.org/
  QBTC: https://www.qbtc.com/
  'Safe Trade': https://www.safe.trade/

broadcasts:
  'October 23': /assets/broadcasts/october-23-2018.ogg
  'November 6': /assets/broadcasts/november-6-2018.ogg
  'November 20': /assets/broadcasts/november-20-2018.ogg


pool:
  website: https://pool.pigeoncoin.org
  address: https://pool.pigeoncoin.org:3663

explorer:
  website: https://explorer.pigeoncoin.org

donate:
  pgn: PDiZ89gk5HMqwrcGp6Hs9WdgFALzLbD4HG
  btc: 1NaVP4cKiWY6MxSDkTCZ2kh5Xm3coA27Qv

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# collections:
# - roadmap

sass:
  sass_dir: _sass
  style: compressed


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
